### PR TITLE
fix(bug): ensure accurate color representation on map with DivIcon

### LINKED ISSUE #3450: getHueForEntity color conversion is not working some colors
**Describe the bug**
When we set achromatic colors (black, white, gray), which have no saturation, as an entity marker, then the map markers do not show these colors 

**To Reproduce**

1. Go to 'Children -> Configure data structure -> General Settings'
2. Add a color for the entity, for eg, "#EDF104" and save the entity settings
3. Now go to Matching(/matching) screen and select any child 
4. You will notice that the selected row is getting highlighted, but the map markers are still using the default or old color

**Expected behavior**
All colors should be supported by leaflet markers

**Screenshots**

Image

**Findings**
_It seems the issue is related to the getHue() or getHueForEntity() method _

### PR DESCRIPTION
**Pull request by sadaf895**
- closes #3450

### PR Checklist
_Before you request a manual PR review from someone, please go through all of this list, check the points and mark them checked here.
This helps us reduce the number of review cycles and use the time of our core reviewers more effectively._

- [x] all automatic CI checks pass (🟢)
  - i.e. code formatting (`ng lint`) passes
  - i.e. unit tests (`ng test`) passes
  - in some cases unit test coverage can be difficult to achieve. If that or any other CI check fails, you can also leave a short comment here why this should be accepted anyway.
- [x] manually tested (all) required functionality described in the issue  manually yourself on the final version of the code (developer)
- [x] reviewed the "Files changed" section of the PR briefly yourself to check for any unwanted changes
   - e.g. clean up debugging console.log statements, disabled tests, ...
   - please also avoid changes that are not directly related to the issue of the PR, even small code reformatings make the review process much more complex
- [x] 🚦 PR status is changed to "Ready for Review"
  - while you are still working on initial implementation, keep the PR in "Draft" status
  - once you are done with your initial work, change to "Ready for Review". This will trigger some additional automated checks and reviews.
  - (PR = "Ready for Review" does not immediately request a manual review yet, first complete the further checks below)
- [x] marked each code review comment as resolved OR commented on it with a question, if unsure
  - both implementing suggestions of automatic code review or discarding them as not applicable is okay
- [x] all checkboxes in this checklist are checked (to show the reviewer this really is ready)
- [x] 🚦 moved the issue related to this PR to Status "Functional Review" to request a personal review

⏪ if issues are commented from testing or code review, make changes. Please then re-check every item of the checklist here again.

-----
### Remaining TODOs:
- [ ] unit tests

## Summary by CodeRabbit

* **Refactor**
  * Map markers now use direct color values for colored markers, with a default gray fallback when no color is provided.
  * Highlighting and opacity handling simplified and applied only to colored markers for more consistent visuals.
  * Removed the previous hue-based coloring approach, yielding cleaner rendering and easier future maintenance.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/app/features/location/map/map.component.ts [hunk 1]
```diff
@@ -163,10 +163,8 @@ export class MapComponent implements AfterViewInit {
     this.map.on("zoomend", () => {
       const allMarkers = this.markerClusterGroup.getLayers() as L.Marker[];
       allMarkers.forEach((marker: any) => {
-        const entity = marker["entity"];
-        const highlighted = marker["highlighted"];
-        if (entity) {
-          this.addMarkerStyle(marker, entity, highlighted);
+        if (marker["hasDivIcon"]) {
```
Comment (sleidig) [inline src/app/features/location/map/map.component.ts]: does that mean an object without color will not get any pin?

I think it may be more intuitive behavior if we set a default (grey?) color then and do not have a special "hasDivIcon" condition at all. Unless I am missing some edge case or aspect here?
