### PR TITLE
 JSON Editor for reports seems to trigger lots of errors (in logs) 

### LINKED ISSUE #3821: JSON Editor for reports seems to trigger lots of errors (in logs)
Sentry Issue: [AAM-DIGITAL-6S2](https://aam-digital.sentry.io/issues/7362701545/?referrer=github_integration)

```
Error: No tile at position 3457
  at Array.map (<anonymous>)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Abhinegi2**
- closes #3821

### PR Checklist
_Before you request a manual PR review from someone, please go through all of this list, check the points and mark them checked here.
This helps us reduce the number of review cycles and use the time of our core reviewers more effectively._

- [x] all automatic CI checks pass (🟢)
  - i.e. code formatting (`ng lint`) passes
  - i.e. unit tests (`ng test`) passes
  - in some cases unit test coverage can be difficult to achieve. If that or any other CI check fails, you can also leave a short comment here why this should be accepted anyway.
- [x] manually tested (all) required functionality described in the issue  manually yourself on the final version of the code (developer)
- [x] reviewed the "Files changed" section of the PR briefly yourself to check for any unwanted changes
   - e.g. clean up debugging console.log statements, disabled tests, ...
   - please also avoid changes that are not directly related to the issue of the PR, even small code reformatings make the review process much more complex
- [x] 🚦 PR status is changed to "Ready for Review"
  - while you are still working on initial implementation, keep the PR in "Draft" status
  - once you are done with your initial work, change to "Ready for Review". This will trigger some additional automated checks and reviews.
  - (PR = "Ready for Review" does not immediately request a manual review yet, first complete the further checks below)
- [x] marked each code review comment as resolved OR commented on it with a question, if unsure
  - both implementing suggestions of automatic code review or discarding them as not applicable is okay
- [x] all checkboxes in this checklist are checked (to show the reviewer this really is ready)
- [x] 🚦 moved the issue related to this PR to Status "Functional Review" to request a personal review

⏪ if issues are commented from testing or code review, make changes. Please then re-check every item of the checklist here again.

-----
### Remaining TODOs:
- [ ] unit tests

## Summary by CodeRabbit

* **Bug Fixes**
  * JSON editor now prevents switching to text mode when large string values are present, avoiding potential data loss during editing sessions.
  * Editor resources are properly cleaned up when closing the editor to prevent lingering state.

* **Improvements**
  * Smarter initial mode selection and more reliable mode-switch handling for a smoother editing experience.

### CODE REVIEW

File: src/app/core/admin/json-editor/json-editor.component.ts [hunk 1]
```diff
@@ -31,17 +45,39 @@ export class JsonEditorComponent
...
-    createJSONEditor({
+    const initialContent: Content = {
+      json: this.ngControl?.control?.value ?? {},
+    };
+    this.textModeDisabledForSession =
+      this.shouldDisableTextModeForContent(initialContent);
+    this.createEditor(
+      initialContent,
+      this.textModeDisabledForSession ? Mode.tree : Mode.text,
+    );
```
[the remark this answers is not in the document]
Comment (Abhinegi2) [reply src/app/core/admin/json-editor/json-editor.component.ts:75]: I tried, but it’s not working. After implementing your suggestion, the same errors are appearing again.

File: src/app/core/admin/json-editor/json-editor.component.ts [hunk 2]
```diff
@@ -31,17 +45,39 @@ export class JsonEditorComponent
...
+
   /**
    * Initializes the JSON editor and sets up event handlers.
    */
   private initializeJSONEditor(): void {
-    createJSONEditor({
+    const initialContent: Content = {
+      json: this.ngControl?.control?.value ?? {},
+    };
+    this.textModeDisabledForSession =
```
Comment (sadaf895) [inline src/app/core/admin/json-editor/json-editor.component.ts:70]: textModeDisabledForSession is computed only from initialContent here. What prevents a later tree edit from introducing a long string and leaving this flag stale? Should we recompute the guard whenever content changes?

Comment (Abhinegi2) [reply src/app/core/admin/json-editor/json-editor.component.ts:70]: @sadaf895  I tried that approach, but the same issue still comes up afterward. CodeRabbit has also raised the same concern, you can check it here - https://github.com/Aam-Digital/ndb-core/pull/3839#discussion_r3021101419

Comment (sadaf895) [reply src/app/core/admin/json-editor/json-editor.component.ts]: I checked the thread and I agree with the timing concern. But does it fully solve the issue yet ?

**Review by sadaf895 — APPROVED** [review]
LGTM!

File: src/app/core/admin/json-editor/json-editor.component.ts [hunk 3]
```diff
@@ -53,12 +89,54 @@ export class JsonEditorComponent
...
+  private shouldDisableTextModeForContent(content: Content): boolean {
+    if (!("json" in content)) {
+      return false;
+    }
+
+    return this.hasLongString(content.json);
+  }
+
+  /**
+   * Recursively checks whether the JSON value contains at least one long string.
```
Comment (sleidig) [inline src/app/core/admin/json-editor/json-editor.component.ts:131]: Can you explain in the comment why long strings are problematic and therefore why these extra steps are necessary, please?

If lengthy, maybe add in the github issue and link to that from the comment

**Review by sleidig — APPROVED** [review]
