### PR TITLE
fix: prevent invalid dropdown options to be added

### LINKED ISSUE #2491: options of configurable enum sometimes broken (missing id)

### PR DESCRIPTION
**Pull request by sleidig**
fixes #2491

### CODE REVIEW

File: src/app/core/basic-datatypes/configurable-enum/configurable-enum.ts [hunk 1]
```diff
@@ -2,12 +2,73 @@ import { Entity } from "../../entity/model/entity";
...
+
   constructor(id?: string, values: ConfigurableEnumValue[] = []) {
     super(id);
     this.values = values;
   }
+
+  /**
+   * Add a new valid option to the enum values, if it is not a duplicate or invalid.
+   * Returns the newly added option upon success.
+   * @param newOptionInput String of option object to be added
```
Comment (sleidig) [inline src/app/core/basic-datatypes/configurable-enum/configurable-enum.ts:19]:
```suggestion
   * @param newOptionInput String or option object to be added
```
