### PR TITLE
fix: improve notification performance 

### LINKED ISSUE #3548: app gets extremely slow when there are many (300+) NotificationEvents

### PR DESCRIPTION
**Pull request by sadaf895**
- closes #3548

### PR Checklist
_Before you request a manual PR review from someone, please go through all of this list, check the points and mark them checked here.
This helps us reduce the number of review cycles and use the time of our core reviewers more effectively._

- [ ] all automatic CI checks pass (🟢)
  - i.e. code formatting (`ng lint`) passes
  - i.e. unit tests (`ng test`) passes
  - in some cases unit test coverage can be difficult to achieve. If that or any other CI check fails, you can also leave a short comment here why this should be accepted anyway.
- [ ] manually tested (all) required functionality described in the issue  manually yourself on the final version of the code (developer)
- [ ] reviewed the "Files changed" section of the PR briefly yourself to check for any unwanted changes
   - e.g. clean up debugging console.log statements, disabled tests, ...
   - please also avoid changes that are not directly related to the issue of the PR, even small code reformatings make the review process much more complex
- [ ] 🚦 PR status is changed to "Ready for Review"
  - while you are still working on initial implementation, keep the PR in "Draft" status
  - once you are done with your initial work, change to "Ready for Review". This will trigger some additional automated checks and reviews.
  - (PR = "Ready for Review" does not immediately request a manual review yet, first complete the further checks below)
- [ ] marked each code review comment as resolved OR commented on it with a question, if unsure
  - both implementing suggestions of automatic code review or discarding them as not applicable is okay
- [ ] all checkboxes in this checklist are checked (to show the reviewer this really is ready)
- [ ] 🚦 moved the issue related to this PR to Status "Functional Review" to request a personal review

⏪ if issues are commented from testing or code review, make changes. Please then re-check every item of the checklist here again.

-----
### Remaining TODOs:
- [ ] unit tests

## Summary by CodeRabbit

* **New Features**
  * Added pagination to Notifications with "Load more" buttons on All and Unread tabs to fetch additional items on demand.
* **Bug Fixes / Improvements**
  * Notification lists now show the correct subset for each tab and the unread badge reliably reflects current unread counts.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/app/features/notification/notification.component.ts [hunk 1]
```diff
@@ -64,10 +93,74 @@ export class NotificationComponent implements OnInit {
...
     });
 
+    // REPRODUCE BUG #3548: Skip loading real notifications, use fake ones instead
     this.loadAndProcessNotifications();
     this.listenToEntityUpdates();
 
     this.checkNotificationConfigStatus();
+
+    // Generate fake notifications WITH entity refs to test realistic scenario
+    this.reproduceSlownessWithEntityRefs(800);
```
Comment (sadaf895) [inline src/app/features/notification/notification.component.ts]: Generating the fake notification code block need to be removed after the final testing and before the merge.

File: src/app/features/notification/notification.component.ts [hunk 2]
```diff
@@ -53,6 +53,35 @@ export class NotificationComponent implements OnInit {
...
+
+  /** Check if there are more notifications to load in "All" tab */
+  get hasMoreAllNotifications(): boolean {
+    return this.allNotifications.length > this.displayLimitAll;
+  }
+
+  /** Check if there are more notifications to load in "Unread" tab */
+  get hasMoreUnreadNotifications(): boolean {
+    return this.unreadNotifications.length > this.displayLimitUnread;
+  }
```
Comment (sleidig) [inline src/app/features/notification/notification.component.ts]: getters are function calls that get called very often during change detection (see #1087), so we should avoid them and instead rather create properties to avoid any further performance impact (although it is already really fast now)

**Review by sleidig — APPROVED** [review]
Looks clean and seems to avoid any performance issues. Thanks for the quick resolution, @sadaf895 🙏
