### PR TITLE
inheritance breaks Details View if source entity ID is not found 

### LINKED ISSUE #3649: inheritance breaks Details View if source entity ID is not found
**Describe the bug**
Views can become completly broken with a missing (or not accessible due to permissions) entity, if there is an inheritance rule based on that entity field.

**To Reproduce**

Example: a missing "User" entity as Note.authors.
Reproducible example for TEST Note (Feb 9th): https://dev.aam-digital.net/note?date=1

1. Config with an inheritance based on the Note.authors field, e.g.
```
"defaultValue": {
  "mode": "inherited-field",
  "config": {
    "sourceReferenceField": "authors",
    "sourceValueField": "phone"
  }
}
```
3. Set an invalid / missing ID in a Note's `authors` field through the DB
4. Click on the Note in the list. You see only the loading screen and an error on the console. The note cannot be displayed

### PR DESCRIPTION
**Pull request by Abhinegi2**
- closes #3649

### PR Checklist
_Before you request a manual PR review from someone, please go through all of this list, check the points and mark them checked here.
This helps us reduce the number of review cycles and use the time of our core reviewers more effectively._

- [ ] all automatic CI checks pass (🟢)
  - i.e. code formatting (`ng lint`) passes
  - i.e. unit tests (`ng test`) passes
  - in some cases unit test coverage can be difficult to achieve. If that or any other CI check fails, you can also leave a short comment here why this should be accepted anyway.
- [ ] manually tested (all) required functionality described in the issue  manually yourself on the final version of the code (developer)
- [ ] reviewed the "Files changed" section of the PR briefly yourself to check for any unwanted changes
   - e.g. clean up debugging console.log statements, disabled tests, ...
   - please also avoid changes that are not directly related to the issue of the PR, even small code reformatings make the review process much more complex
- [ ] 🚦 PR status is changed to "Ready for Review"
  - while you are still working on initial implementation, keep the PR in "Draft" status
  - once you are done with your initial work, change to "Ready for Review". This will trigger some additional automated checks and reviews.
  - (PR = "Ready for Review" does not immediately request a manual review yet, first complete the further checks below)
- [ ] marked each code review comment as resolved OR commented on it with a question, if unsure
  - both implementing suggestions of automatic code review or discarding them as not applicable is okay
- [ ] all checkboxes in this checklist are checked (to show the reviewer this really is ready)
- [ ] 🚦 moved the issue related to this PR to Status "Functional Review" to request a personal review

⏪ if issues are commented from testing or code review, make changes. Please then re-check every item of the checklist here again.

-----
### Remaining TODOs:
- [ ] unit tests

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error handling when loading parent entities during field initialization to prevent application failures.
  * Refined field filtering in entity forms to display only properly labeled fields.

* **Tests**
  * Added test coverage for error scenarios in inherited field handling.

### CODE REVIEW

File: src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.ts [hunk 1]
```diff
@@ -207,7 +207,7 @@ export class AdminEntityFormComponent implements OnChanges {
     );
     const unusedFields = Array.from(this.entityType.schema.entries())
       .filter(([key]) => !usedFields.some((x) => x.id === key))
-      .filter(([key, value]) => !value.isInternalField) // no technical, internal fields
+      .filter(([key, value]) => !value.isInternalField && value.label) // no technical, internal fields and must have label
```
Comment (Abhinegi2) [inline src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.ts]: - Field 'childrenAttendance' does not have a label
- Field 'relatesTo' does not have a label
