### PR TITLE
 "Merge" should also check user account (and use entity with an account as the primary, remaining entity) 

### LINKED ISSUE #3619: "Merge" should also check user account (and use entity with an account as the primary, remaining entity)
**Describe the bug**
When merging two entities using the bulk action, it can happen that one of the entities has a Keycloak user account associated. It then depends on luck that the entity ID linked in the user account is also the one that remains in the database.

Instead, we should:
- check user accounts for both merging entities
- display them in the comparison screen
- by default, select that entity as the primary (whose _id remains in the DB), which has an account (if only one of the two has an account)
- warn the user that an account will be orphaned (continue to exist but not have a valid entity linked to it), when the merge is confirmed and an account is linked to the entity that gets deleted by the merge (e.g. because both entities had an account)

### PR DESCRIPTION
**Pull request by Abhinegi2**
- closes #3619

### PR Checklist
_Before you request a manual PR review from someone, please go through all of this list, check the points and mark them checked here.
This helps us reduce the number of review cycles and use the time of our core reviewers more effectively._

- [ ] all automatic CI checks pass (🟢)
  - i.e. code formatting (`ng lint`) passes
  - i.e. unit tests (`ng test`) passes
  - in some cases unit test coverage can be difficult to achieve. If that or any other CI check fails, you can also leave a short comment here why this should be accepted anyway.
- [ ] manually tested (all) required functionality described in the issue  manually yourself on the final version of the code (developer)
- [ ] reviewed the "Files changed" section of the PR briefly yourself to check for any unwanted changes
   - e.g. clean up debugging console.log statements, disabled tests, ...
   - please also avoid changes that are not directly related to the issue of the PR, even small code reformatings make the review process much more complex
- [ ] 🚦 PR status is changed to "Ready for Review"
  - while you are still working on initial implementation, keep the PR in "Draft" status
  - once you are done with your initial work, change to "Ready for Review". This will trigger some additional automated checks and reviews.
  - (PR = "Ready for Review" does not immediately request a manual review yet, first complete the further checks below)
- [ ] marked each code review comment as resolved OR commented on it with a question, if unsure
  - both implementing suggestions of automatic code review or discarding them as not applicable is okay
- [ ] all checkboxes in this checklist are checked (to show the reviewer this really is ready)
- [ ] 🚦 moved the issue related to this PR to Status "Functional Review" to request a personal review

⏪ if issues are commented from testing or code review, make changes. Please then re-check every item of the checklist here again.

-----
### Remaining TODOs:
- [ ] unit tests

## Summary by CodeRabbit

* **New Features**
  * Editable account email and role selection with validation and preview during bulk record merges
  * Option to create entity forms without applying schema default values

* **Refactor**
  * Bulk-merge UI switched to OnPush change detection for improved performance

* **Tests**
  * Expanded coverage for user-account handling, merge confirmations, and form default-value behavior

* **Behavior**
  * Merge flow prompts confirmations for account-linked records and removes discarded records’ user accounts when applicable

### CODE REVIEW

**Review by sleidig — COMMENTED** [review]
Really good code, great work 😃 

I raised a few general questions and also added explicitly a list of scenarios including edge cases to the issue now: https://github.com/Aam-Digital/ndb-core/issues/3619
(I think most are covered already but please have a look)

**Review by sleidig — CHANGES_REQUESTED** [review]
I stumbled upon an edge case issue:

1. Merge two accounts
2. with account for Record A disabled
3. ... will try to send a email verification, which fails for disabled account
4. ... and also, either way I would not want to verify my user account again after a merge.

Maybe the better interface would be to have a dropdown with one or more accounts (represented by their email) and just select which (if any) account you want to keep linked to the merged record? No option to change the email at this point.

**Comment by Abhinegi2** [comment]
@sleidig could you please test this again and let me know if anything still needs to be adjusted?

File: src/app/features/de-duplication/bulk-merge-records/merge-account-section/merge-account-section.component.ts [hunk 1]
```diff
@@ -0,0 +1,316 @@
...
+
+  selectedAccountEmail(): string {
+    const selectedIndex = this.selectedAccountIndex();
+    if (selectedIndex == null) return "-";
+    return this.entityAccounts()[selectedIndex]?.email ?? "-";
+  }
+
+  hasAccountRoles(index: number): boolean {
+    return this.getAccountRoles(index).length > 0;
+  }
```
Comment (sleidig) [inline src/app/features/de-duplication/bulk-merge-records/merge-account-section/merge-account-section.component.ts]: wouldn't it be easier to put such stuff into the html template so that the .ts class can focus on logic?

File: src/app/features/de-duplication/bulk-merge-records/merge-account-section/merge-account-section.component.html [hunk 2]
```diff
@@ -0,0 +1,117 @@
+@if (
+  entityConstructor().enableUserAccounts &&
+  (hasAnyUserAccount() || accountLoadError())
+) {
+  <div class="account-panel-wrapper">
+    <mat-expansion-panel [expanded]="hasAnyUserAccount()">
+      <mat-expansion-panel-header>
+        <mat-panel-title i18n>User Account Fields</mat-panel-title>
```
Comment (sleidig) [inline src/app/features/de-duplication/bulk-merge-records/merge-account-section/merge-account-section.component.html]:
```suggestion
        <mat-panel-title i18n>Linked User Accounts</mat-panel-title>
```

**Review by sleidig — APPROVED** [review]
Functionally works very well now. Code also looks good.

Do you also see the following?
> sentry-angular.mjs:167 Error: Cannot find control with unspecified name attribute
    at _throwError (forms.mjs:1767:9)
    at setUpControl (forms.mjs:1633:19)

**Comment by Abhinegi2** [comment]
> Functionally works very well now. Code also looks good.
> 
> Do you also see the following?
> 
> > sentry-angular.mjs:167 Error: Cannot find control with unspecified name attribute
> > at _throwError (forms.mjs:1767:9)
> > at setUpControl (forms.mjs:1633:19)

I also saw the same error in the console. I've fixed that as well. It was happening because the form control was initially null.

**Review by sleidig — APPROVED** [review]
