### PR TITLE
Sort roll call participants

### LINKED ISSUE #931: Events created from RecurringActivity should omit deleted participants
**Describe the bug**
If a child is deleted but still linked to a RecurringActivity, we do skip that participant during the one-by-one roll call but it is still added to the resulting event and then shown in the participant list of the note/event details without a name:
image

**To Reproduce**
1. Find or create a "Recurring Activity" and choose one of the linked participants
2. Go to the Child Details of that participant and delete it
3. "Record Attendance" (here the deleted participant will not show)
4. Open the Details View of the resulting Event Note (e.g. through "Notes" list with "include events" toggle active)
5. Here the delete participant still shows up as a nameless line

**Expected behavior**
The Event should not at all be linked with deleted records, only existing participants of the RecuringActivity should be linked to new Event entities.

### PR DESCRIPTION
**Pull request by sleidig**
on request of one of our clients, this PR adds the option to configure a property by which participants are ordered when shown one after another in the "record attendance" / "roll call" workflow.

also, fixes #931

### CODE REVIEW

File: src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts [hunk 1]
```diff
@@ -64,9 +76,14 @@ export class RollCallComponent implements OnInit {
...
-    this.loadAttendanceStatusTypes();
-    await this.loadParticipants();
+  async ngOnChanges(changes: SimpleChanges) {
+    if (changes.eventEntity) {
+      this.loadAttendanceStatusTypes();
+      await this.loadParticipants();
+    }
+    if (changes.sortParticipantsBy) {
+      this.sortParticipants();
+    }
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts:86]:
```suggestion
    this.sortParticipants();
```

If there is the check on line 119 I don't think there is a second check needed here

File: src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.ts [hunk 2]
```diff
@@ -1,13 +1,25 @@
...
 import { Note } from "../../notes/model/note";
+import { ActivatedRoute } from "@angular/router";
+import { RouteData } from "../../../core/view/dynamic-routing/view-config.interface";
+
+/**
+ * additional config specifically for AddDayAttendanceComponent
+ */
+export interface AddDayAttendanceConfig {
+  /** (optional) property name of the participant entities by which they are sorted for the roll call */
+  sortParticipantsBy: string;
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.ts:12]:
```suggestion
  sortParticipantsBy?: string;
```

File: src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html [hunk 3]
```diff
@@ -20,6 +20,7 @@
     <app-roll-call
       *ngIf="currentStage === 1"
       [eventEntity]="event"
+      [sortParticipantsBy]="config?.sortParticipantsBy"
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html:23]: Either this shouldn't be optional or the config itself should be

File: src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.ts [hunk 4]
```diff
@@ -20,7 +32,16 @@ export class AddDayAttendanceComponent {
     $localize`:One of the stages while recording child-attendances:Record Attendance`,
   ];
 
-  constructor(private entityMapper: EntityMapperService) {}
+  constructor(
+    private entityMapper: EntityMapperService,
+    private route: ActivatedRoute
+  ) {
+    this.route.data.subscribe(
+      async (data: RouteData<AddDayAttendanceConfig>) => {
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.ts:40]:
```suggestion
      (data: RouteData<AddDayAttendanceConfig>) => {
```

File: src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts [hunk 5]
```diff
@@ -100,22 +109,19 @@ describe("RollCallComponent", () => {
...
-
-    component.ngOnInit();
+    component.ngOnChanges(dummyChanges);
     tick();
 
-    expect(component.entries.map((e) => e.child)).toEqual([existingChild]);
+    expect(component.entries.map((e) => e.child)).toEqual([participant1]);
+    expect(
+      component.eventEntity.children.includes(nonExistingChildId)
+    ).toBeFalse();
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts:124]:
```suggestion
    expect(component.eventEntity.children).not.toContain(nonExistingChildId);
```

File: src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts [hunk 6]
```diff
@@ -238,4 +229,38 @@ describe("RollCallComponent", () => {
 
     expect(confirmationDialogService.openDialog).toHaveBeenCalled();
   });
+
+  it("should sort participants based on configured property", fakeAsync(() => {
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts:233]: Maybe add another test case for a different property here?

File: src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts [hunk 7]
```diff
@@ -33,12 +40,17 @@ import { ConfirmationDialogService } from "../../../../core/confirmation-dialog/
...
+export class RollCallComponent implements OnChanges {
   /**
    * The event to be displayed and edited.
    */
   @Input() eventEntity: Note;
 
+  /**
+   * (optional) property name of the participant entities by which they are sorted
+   */
+  @Input() sortParticipantsBy: string;
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts:52]:
```suggestion
  @Input() sortParticipantsBy?: string;
```

File: src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts [hunk 8]
```diff
@@ -98,6 +116,16 @@ export class RollCallComponent implements OnInit {
...
+  private sortParticipants() {
+    if (!this.sortParticipantsBy) {
+      return;
+    }
+
+    this.entries.sort((a, b) => a.child.name.localeCompare(b.child.name));
+    // also sort the participants in the Note entity itself for display in details view later
+    this.eventEntity.children = this.entries.map((e) => e.child.getId());
+  }
+
```
Comment (Schottkyc137) [inline src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts:128]: Am I missing something here or is the actual value of `this.sortParticipantsBy` ignored (and the entities are only sorted by name?)

**Review by Schottkyc137 — CHANGES_REQUESTED** [review]

File: src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts (hunk 8 above)
Comment (sleidig) [reply src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts:128]: damn it ... good thing I put this up for review. You are absolutely right :sweat_smile:

File: src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts (hunk 1 above)
Comment (sleidig) [reply src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts:86]: it's not necessary to trigger a new sorting though, if that input did not change (especially if any completely unrelated inputs may be added in the future).

I included a sort in the loadParticipants now, however, to ensure this reflects the current sort state if new data comes in

File: src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html (hunk 3 above)
Comment (sleidig) [reply src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html:23]: sorry, I don't think I got what you mean.

To keep backward compatibility as well as the option of a simple setup, this view may not have any config at all - therefore `config?.`
How would you write this here differently with as few lines of code?

Comment (Schottkyc137) [reply src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html:23]: Sorry that I haven't made this more clear.... In the component the config is declared as 
```ts
config: AddDayAttendanceConfig;
```
So what I meant was to either make it non-optional in the template, or make the config in the component itself optional. Seems like the second option is better then :D

Comment (sleidig) [reply src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html:23]: ah, got it. Done :+1:

**Review by Schottkyc137 — APPROVED** [review]
I think this looks quite good now and will make a nice improvement 👍
