### PR TITLE
fix: prevent saving a field with identical label

### LINKED ISSUE #3634: Prevent saving a field with identical label of another field
**Describe the bug**
We ensure field IDs are unique but currently users can edit the Label to be exactly the same for multiple fields. This can create a lot of confusion when importing data or configuring other screens. We should check and prevent people from using the exact same label twice.

### PR DESCRIPTION
**Pull request by sadaf895**
- closes #3634

### PR Checklist
_Before you request a manual PR review from someone, please go through all of this list, check the points and mark them checked here.
This helps us reduce the number of review cycles and use the time of our core reviewers more effectively._

- [x] all automatic CI checks pass (🟢)
  - i.e. code formatting (`ng lint`) passes
  - i.e. unit tests (`ng test`) passes
  - in some cases unit test coverage can be difficult to achieve. If that or any other CI check fails, you can also leave a short comment here why this should be accepted anyway.
- [x] manually tested (all) required functionality described in the issue  manually yourself on the final version of the code (developer)
- [x] reviewed the "Files changed" section of the PR briefly yourself to check for any unwanted changes
   - e.g. clean up debugging console.log statements, disabled tests, ...
   - please also avoid changes that are not directly related to the issue of the PR, even small code reformatings make the review process much more complex
- [x] 🚦 PR status is changed to "Ready for Review"
  - while you are still working on initial implementation, keep the PR in "Draft" status
  - once you are done with your initial work, change to "Ready for Review". This will trigger some additional automated checks and reviews.
  - (PR = "Ready for Review" does not immediately request a manual review yet, first complete the further checks below)
- [x] marked each code review comment as resolved OR commented on it with a question, if unsure
  - both implementing suggestions of automatic code review or discarding them as not applicable is okay
- [x] all checkboxes in this checklist are checked (to show the reviewer this really is ready)
- [x] 🚦 moved the issue related to this PR to Status "Functional Review" to request a personal review

⏪ if issues are commented from testing or code review, make changes. Please then re-check every item of the checklist here again.

-----
### Remaining TODOs:
- [x] unit tests

## Summary by CodeRabbit

* **New Features**
  * UI now shows a duplicate-label validation message when a label conflicts with existing fields.

* **Tests**
  * Extended coverage for label uniqueness and the new generic uniqueness validator, including edit and case-insensitive scenarios; retired the old id-specific validator tests.

* **Refactor**
  * Replaced the id-specific uniqueness check with a reusable generic uniqueness validator used for ids and labels.

### CODE REVIEW

File: src/app/core/common-components/entity-form/unique-label-validator/unique-label-validator.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+/**
+ * Validator to ensure that a field label is unique within an entity type's schema.
+ * Labels are compared case-insensitively with trimmed whitespace.
+ *
+ * @param entityType The entity type whose schema contains all field labels
+ * @param currentFieldId Optional ID of the field being edited (to exclude it from comparison)
+ * @returns An async validator function
+ */
+export function uniqueLabelValidator(
```
Comment (sleidig) [inline src/app/core/common-components/entity-form/unique-label-validator/unique-label-validator.ts]: This is almost identical to the logic behind `uniqueIdValidator`.

Let's merge both validators?

If we add another parameter `requiredUniqueProperty` (or something similar), we could probably use the same validator with `"id"` or with `"label"`.

What do you think, @sadaf895 ?
