### PR TITLE
fix: show new health an observation records immediately

### LINKED ISSUE #2186: [Regression] New health checks are not directly added to table
**To Reproduce**
1. Go to 'Child details'
2. Click on 'Health'
3. Click '+' button
4. Fill data
5. Click 'save'
6. New entry is not visible in table
7. After re-entering the view, the entry is visible

**Expected behavior**
Entry should instantly be visible.

**Additional context**
This is probably because of the changes in #2142. Now the changes listener is only applied in the `RelatedEntitiesComponent`, which is not (yet) used in the `HealthCheckComponent`, and not in the entities table as before.
Its probably easiest to also start using `RelatedEntitiesComponent` and check whether other components might also be affected by the same issue.

### PR DESCRIPTION
**Pull request by sleidig**
fixes #2186

### CODE REVIEW

File: src/app/core/config/config-fix.ts [hunk 1]
```diff
@@ -640,14 +640,16 @@ export const defaultJsonConfig = {
...
-              "config": [
-                "date",
-                { "id": "isMotivatedDuringClass", "visibleFrom": "lg" },
-                { "id": "isParticipatingInClass", "visibleFrom": "lg" },
-                { "id": "isInteractingWithOthers", "visibleFrom": "lg" },
-                { "id": "doesHomework", "visibleFrom": "lg" },
-                { "id": "asksQuestions", "visibleFrom": "lg" },
-              ]
+              "config": {
+                "columns": [
```
Comment (TheSlimvReal) [inline src/app/core/config/config-fix.ts:644]: Seems to be backwards compatible but I added the migration to our list in #2066

**Review by TheSlimvReal — APPROVED** [review]
Thanks for the quick fix
